.github/workflows/tests.yml

For each PR the actions are executed twice. Only running against a PR is sufficient.

Run actions only against pull requests.

---

CODE_OF_CONDUCT.md

Update link to point to the new repo

[MRG] Update CODE_OF_CONDUCT.md: Repo link

---

.github/workflows/tests.yml

as discovered in: https://github.com/py-pdf/pypdf_table_extraction/issues/29#issuecomment-2292230072

[FIX]:  codecov action

---

camelot/__version__.py

The version of this file is used by the documentation.

[UPD] Update version, name to new repo

---

.github/ISSUE_TEMPLATE/bug_report.md
camelot/backends/ghostscript_backend.py
pyproject.toml
tests/test_common.py

Part of #9
This pr is just changing the url's in the code.

[IMP] Update readthedocs url

---

.github/workflows/tests.yml

Bump github actions/upload-download artifact to V4.
Replaces #67 and #75

Use Up/down artifactv4

---

tests/test_cli.py

forward of: https://github.com/camelot-dev/camelot/pull/250

[MRG] added test to validate when plot_type is None

---

.github/workflows/tests.yml
camelot/backends/ghostscript_backend.py
tests/test_lattice.py

Fix missing DLL errors
Enable Ghostscript install on CI
Re-activate lattice parser unit tests on windows
fixes: https://github.com/atlanhq/camelot/issues/476 https://github.com/atlanhq/camelot/issues/282 https://github.com/camelot-dev/camelot/issues/154

[FIX]/[IMP] Windows Support

---

camelot/parsers/lattice.py
tests/test_errors.py

Remove Ghostscript deprecation warning

---

pyproject.toml

Version bump to 0.0.2 release

---

camelot/utils.py

Fix variable naming and qa checks

---

camelot/backends/base.py
camelot/backends/ghostscript_backend.py
camelot/backends/image_conversion.py
camelot/backends/poppler_backend.py

If typing is the way we want to go, this PR adds it for the backends.

Add typing for camelot/backends

---

camelot/backends/ghostscript_backend.py
camelot/backends/image_conversion.py
camelot/parsers/lattice.py
camelot/utils.py
tests/test_common.py
tests/test_errors.py
tests/test_image_conversion_backend.py

[Fix] Image conversion backend Fallback, More verbose backend exception feedback

---

camelot/parsers/base.py
tests/test_errors.py

Rebrand Image based error message

---

camelot/cli.py

Fixup explanation of the Hybrid and Network parser.

[IMP] CLI Documentation

---

camelot/utils.py

1. **Removed Unnecessary Checks**: The code now handles edge cases (when `point` is less than the first element or greater than the last element) upfront to simplify the binary search logic.
2. **Simplified Logic**: The binary search loop has been streamlined. The conditions for moving `left` and `right` have been clarified, focusing on the mid-point comparison without extra checks.
3. **Post-Loop Calculation**: After the binary search loop, we directly check the closest points by comparing the distances of the found indices to the `point`. This reduces redundancy and improves clarity.
4. **Type Annotations**: The docstring is improved to specify the types of parameters and return values, which enhances the understanding of this function.
Overall, this refactored function maintains the …

[REF] get_index_closest_point

---

camelot/image_processing.py

Flake8 fixes and reduce complexity.

[REF]: find lines

---

camelot/core.py

1. **Dedicated Methods**: The code has been split into several dedicated methods:
- `_set_vertical_edges`: Handles the logic for setting vertical edges.
- `_update_vertical_edges`: Updates the edges for vertical lines based on the computed indices.
- `_set_horizontal_edges`: Handles the logic for setting horizontal edges.
- `_update_horizontal_edges`: Updates the edges for horizontal lines based on the computed indices.
- `_find_close_point`: A helper method to find the closest point and has been moved outside of `set_edges` for better organization.
2. **Reduced Complexity**: Each method now has a clear purpose, which reduces the complexity of the `set_edges` method itself. This makes it easier to read and understand.
3. **Maintainability**: With the separate methods for setting vertical …

[REF]: Core Table set edges to reduce complexity

---

camelot/backends/ghostscript_backend.py
camelot/backends/poppler_backend.py
camelot/core.py
camelot/handlers.py

The goal is to have it pass, so pre-commit can be activatd on this repo.

Various Flake8 fixes

---

docs/user/how-it-works.rst
examples/hybrid-parser-step-by-step.ipynb

Step by step explain the network and hybrid parser

:student:  [ADD] Hybrid Parser notebook

---

README.md
camelot/handlers.py
docs/api.rst
docs/dev/contributing.rst
docs/index.rst
docs/user/advanced.rst
docs/user/cli.rst
docs/user/faq.rst
docs/user/how-it-works.rst
docs/user/install-deps.rst
docs/user/install.rst
docs/user/quickstart.rst

Update Documentation Reflect new namespace

---

pyproject.toml

Make plot dependencies optional

---

camelot/utils.py

This fixes IndexError: list index out of range
as reported in: https://github.com/py-pdf/pypdf_table_extraction/issues/210#issuecomment-2467890870

Ref comp whitespace
