py-pdf/pypdf_table_extraction

camelot/utils.py
Since the existing code overwrites `layout` and `dim` in each iteration, it is much more efficient to simply return the `layout` and `dim` of the first page.
I have tested the difference with a 455 page pdf and the optimisation reduces the time spent from 50 to 5 seconds.
=> [MRG] Utils: optimise get_page_layout

camelot/backends/poppler_backend.py
Fix situation where pdftopng is not found if executing python directly from an un-activated environment.
=> Poppler backend: search for pdftopng in current environment

poetry.lock
Safety found 7 vulnerabilities in our lockfile. Running poetry update results in the following updates.
• Installing authlib (1.3.0)
• Installing marshmallow (3.21.0)
• Installing pydantic (1.10.14)
• Installing safety-schemas (0.0.2)
• Installing typer (0.9.0)
• Removing gitdb (4.0.10)
• Removing gitpython (3.1.37)
• Removing smmap (5.0.0)
• Updating attrs (23.1.0 -> 23.2.0)
• Updating babel (2.12.1 -> 2.14.0)
• Updating bandit (1.7.5 -> 1.7.7)
• Updating beautifulsoup4 (4.12.2 -> 4.12.3)
• Updating black (23.7.0 -> 24.2.0)
• Updating certifi (2023.7.22 -> 2024.2.2)
• Updating cffi (1.15.1 -> 1.16.0)
• Updating cfgv (3.3.1 -> 3.4.0)
• Updating chardet (5.1.0 -> 5.2.0)
• Updating charset-normalizer (3.2.0 -> 3.3.2)
• Updating click (8.1.5 -> 8.1.7)
• Updating contourpy (1.1.0 -> 1.1.1)
• …
=> Fix safety issues by update lockfile

.github/workflows/constraints.txt, .github/workflows/release.yml, .github/workflows/tests.yml
As described in https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1383 there is an issue with pipx regarding relative paths. 
Using absolute paths fixes this.
=> Use the absolute path to constraints.txt

.github/workflows/tests.yml
Let's make CI 🟢 again.
Thanks to this source: https://jonathansoma.com/everything/pdfs/camelot-ghostscript/
=> Fix CI: 🟢 mac-os specific ghostscript install

camelot/core.py, tests/test_common.py
```python
tables = camelot.read_pdf(filename)
for idx, table in enumerate(tables):   # Warining: Expected type 'Iterable[_T]', got 'TableList' instead  in pycharm
pass
```
=> add __iter__() for TableList to support enumerate()

.github/workflows/tests.yml
The test workflow is targeted to run against `master`, but the repo uses `main` so need to update that.
=> [DEV] Run test workflow against main

README.md
Forward port of: https://github.com/atlanhq/camelot/pull/340
=> Update Documentation Syntax

pyproject.toml
Fix coverage combine for windows and macos runner.
Fixes messages like this:
```
home/runner/work/pypdf_table_extraction/pypdf_table_extraction/.nox/coverage/lib/python3.10/site-packages/coverage/report_core.py:115: CoverageWarning: Couldn't parse '/home/runner/work/pypdf_table_extraction/pypdf_table_extraction/D:\a\pypdf_table_extraction\pypdf_table_extraction\camelot\plotting.py': No source for code: '/home/runner/work/pypdf_table_extraction/pypdf_table_extraction/D:\a\pypdf_table_extraction\pypdf_table_extraction\camelot\plotting.py'. (couldnt-parse)
```
=> [FIX]: Fix Github action: Coverage combine

camelot/cli.py, tests/test_cli.py
Bug reported here https://github.com/camelot-dev/camelot/issues/499
Pull to original repository https://github.com/camelot-dev/camelot/pull/500 (commits differs, cause to rebase issues)
=> Added supported for CLI margins option.

camelot/backends/poppler_backend.py
This is silencing/fixing the `S602 subprocess call with shell=True identified, security issue.
`
=> [IMP] Improve poppler subprocess security

docs/requirements.txt, noxfile.py, poetry.lock, pyproject.toml
Switch to opencv headless. To reduce the bloat on server environments.
=> [IMP] Opencv headless

camelot/core.py
Speedup as in https://github.com/camelot-dev/camelot/issues/161
For reference: https://github.com/numpy/numpy/issues/16160
Seems still actual in 2024. My results:
```pycon
import timeit
print(timeit.timeit('np.isclose(0.5, 0, atol=1e-4)', 'import numpy as np', number=10000))
print(timeit.timeit('math.isclose(0.5, 0, abs_tol=1e-4)', 'import math', number=10000))
```
Once ready, prefer to squash and merge.
More performance gains could potentially be realized. But let's do that in a separate PR.
https://github.com/atlanhq/camelot/issues/427
=> Speedup as in https://github.com/camelot-dev/camelot/issues/161

camelot/parsers/base.py, camelot/utils.py
Speedup as in https://github.com/camelot-dev/camelot/issues/161
For reference: https://github.com/numpy/numpy/issues/16160
Seems still actual in 2024. My results:
```pycon
import timeit
print(timeit.timeit('np.isclose(0.5, 0, atol=1e-4)', 'import numpy as np', number=10000))
print(timeit.timeit('math.isclose(0.5, 0, abs_tol=1e-4)', 'import math', number=10000))
```
=> [REF] slow np.isclose to math.isclose

.github/workflows/tests.yml, camelot/core.py, camelot/handlers.py, camelot/utils.py, noxfile.py, poetry.lock, pyproject.toml
- Activate mypy test on github actions
- Add typing_extensions dependency for python < 3.11
- Some typing fixes to make mypy pass
- Added instructions from mypy readme, to graduallly improve typing on existing code base.
Fasttracking this one, to be able to rebase code-refactors so pre-commit can be activated on this repo.
=> Activate mypy type checking

tests/test_cli.py
This silences the warning on unit tests:
```
tests/test_cli.py::test_cli_quiet
/home/runner/work/pypdf_table_extraction/pypdf_table_extraction/camelot/parsers/base.py:122: UserWarning: No tables found on page-1
warnings.warn(f"No tables found on {rootname}")
```
=> [FIX] Warning on test cli quiet

camelot/utils.py
1. **Modular Functions**: The code is broken down into smaller functions (`_process_horizontal_cut`, `_process_vertical_cut`, and `_group_and_process_chars`) to handle specific tasks, making it easier to read and maintain.
2. **Error Handling**: The try-except block was removed since the logic handles cases gracefully without needing to catch exceptions.
3. **Type Hints**: Type hints were added for better code clarity and to help with type checking.
=> [REF] split_textline

camelot/parsers/network.py
Split up the search header function of the network parser to reduce the complexity.
=> [REF] Network parser search header split into sub methods to reduce complexity

camelot/backends/image_conversion.py, camelot/parsers/lattice.py, tests/test_common.py, tests/test_image_conversion_backend.py
=> Fix custom backend functionality

camelot/parsers/network.py
This fixes Flake 8:
B903 Data class should either be immutable or use __slots__ to save memory. Use collections.namedtuple to generate an immutable class, or enumerate the attributes in a __slot__ declaration in the class to leave attributes mutable.
=> Network parser Fix B903

camelot/utils.py
1. **Empty List Check**:
- At the start of the function, I added a condition to check if the `boundaries` list is empty. If it is, the function returns an empty list, preventing any further operations that would lead to index errors.
2. **Minimum Length Check**:
- Although not strictly necessary after the empty check, I added a check to ensure that there is at least one tuple in the `boundaries`. This is more of a safeguard, as the first check already handles the empty case.
=> boundaries to split lines Fix index out of range

camelot/parsers/network.py
Fixes type error unhashable type of the network parser..
1. **Use of Set for Processed Textlines**:
- I changed `textlines_processed` from a dictionary to a set for faster membership testing, which reduces the complexity of checking if a textline has already been processed.
2. **Helper Methods**:
- Introduced `_get_bbox_body` and `_get_full_bbox` methods to encapsulate logic for retrieving the bounding box body and full bounding box, respectively. This reduces complexity and improves readability.
3. **Simplified Logic**:
- Removed unnecessary checks and streamlined the flow of determining the `bbox_body` and `bbox_full`, avoiding deep copying unless absolutely necessary.
4. **Reduced Nested Conditions**:
- Flattened the nested conditions for better clarity and understanding of the flow. …
=> [REF] netw gen bbox

camelot/core.py
1. **Variable Initialization**: We store `len(self.rows)` and `len(self.cols)` in `num_rows` and `num_cols` respectively to avoid recalculating these values on each iteration.
2. **Error Handling**: Before trying to set borders, we check if the number of rows and columns is valid. If either is zero, the method returns early. Additionally, we check if `self.cells` has the expected structure. If not, we raise a `ValueError`.
3. **Looping through Indices**: Instead of using `enumerate()`, use a simple `range()` loop since we only need the index and not the item itself. This can enhance readability and possibly performance.
=> [REF]: core set_border: Improve performance, Fix index out of Range

camelot/parsers/network.py
1. **Using a Separate List for Removal**: Instead of deleting elements from `text_alignment.textlines` while iterating over it, we first collect the indices of elements to remove in a separate list called `to_remove`. This prevents issues that can arise from modifying a list while iterating over it.
2. **Reverse Index Removal**: When removing items, we iterate over `to_remove` in reverse order. This ensures that the indices of elements to be removed do not affect the remaining elements in the list as we delete them.
3. **Clearer Condition for Removal**: The condition checking whether a text line is a singleton remains the same, but moving the deletion logic outside of the inner loop improves clarity and avoids potential errors that could lead to infinite loops.
4. **Termination Flag**: …
=> [REF] remove_unconnected_edges

camelot/parsers/base.py, camelot/parsers/network.py, tests/test_hybrid.py
The first commit is introducing a unit test which was failling with a Keyerror.
The second commit is rather a workaround then a fix.
It let's the parser fail/continue gracefully.
Whichi is desired when using this library in a ETL/Document flow when processing multiple pages.
=> [FIX] hybrid Keyerror

camelot/parsers/network.py
1. **Use of `get` Method**: When retrieving the best alignment, we use `self._textline_to_alignments.get(most_aligned_tl)` instead of direct indexing. This prevents a potential `KeyError` if `most_aligned_tl` is not in the dictionary, which could lead to unexpected behavior.
2. **Early Exit Conditions**: We explicitly check if `best_alignment` is `None` after attempting to retrieve it. This ensures that we do not proceed with calculations if the alignment data is missing.
3. **Sorting and Gap Calculation**: I retained the logic to sort the text lines and calculate gaps. This part of the code is straightforward and unlikely to lead to an infinite loop as long as the input lists are correctly managed.
4. **Returning `None` for Insufficient Data**: The checks for the lengths of the text line …
=> [REF] Compute_plausible_gaps, Efficiency, Stability

poetry.lock, pyproject.toml
PDFium is now used as the standard image conversion backend.
Making it easier to install on a lot of systems by just using the pip package manager.
The ghostscript backend is still available. but moved to an optional dependency group.
It can be installed with `poetry install --with ghostscript`.
Documentation will be updated in a separate pr. Before the next major release.
=> :bomb:  Make Ghostscript an optional dependency :sparkles: 

camelot/handlers.py
Before this pr, each processed page got analyzid 2 times for the layout and dimensions.
This is unnessecary, as we only need to do it for PDF files we are rotating.
This is inspired on:  https://github.com/nexus-lib/camelot/pull/2
=> Eliminated duplicate processes.

camelot/handlers.py, camelot/parsers/base.py, camelot/parsers/hybrid.py, camelot/utils.py, pypdf_table_extraction/utils.py
Originally, Camelot scans 2 to 3 times for whole PDF objects on the page to get 1. Horizontal Texts, 2. Vertical texts, and 3. Images.
This PR is to change it to one scan to get everything.
This is a port of https://github.com/nexus-lib/camelot/pull/1
=> [IMP] reduce pdf object loop
